# This workflow will build a .NET project and upload the binary as an artifact
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish build artifacts
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -o ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stickly-artifacts
        path: ./publish/Stickly.exe
